[workspace]
authors = ["Jesse Robertson <jess.robertson@niwa.co.nz>"]
channels = ["conda-forge"]
name = "logerr"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
loguru = ">=0.7.3,<0.8"
confection = ">=0.1.5,<0.2"
tenacity = ">=9.1.2,<10"

[feature.dev.dependencies]
pytest = "*"
hypothesis = "*"
mypy = "*"
pytest-cov = ">=6.2.1,<7"
ruff = "*"
pre-commit = ">=4.2.0,<5"

[feature.dev.tasks]
test = "pytest tests/ --doctest-modules logerr --cov=logerr --cov-report=term"
test-all = "pytest tests/ --doctest-modules logerr"
typecheck = "mypy logerr"
quality = "ruff check logerr tests && ruff format --check logerr tests"
clean = "rm -rf htmlcov/ site/ .coverage .pytest_cache/ **/__pycache__/ **/*.pyc .mypy_cache/ .hypothesis/"
check-all = { depends-on = ["test", "typecheck", "quality"] }

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocstrings = "*"
mkdocstrings-python = "*"

[feature.docs.tasks]
docs-serve = "mkdocs serve"
docs-build = "mkdocs build"

[environments]
dev = ["dev"] 
docs = ["docs"]
