name: CI

# This workflow runs on the jesserobertson/logerr repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: dev

    - name: Install dependencies
      run: pixi install --environment dev

    - name: Run all checks
      run: pixi run -e dev check-all

    - name: Run coverage 
      run: pixi run -e dev test --cov-report=xml

    - name: Upload coverage reports
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
